import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Web Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sint error
          consectetur modi odio obcaecati tempore dignissimos assumenda, eum
          reiciendis dolores magni autem at debitis voluptas. Rem ipsa deleniti
          autem dignissimos.
        </p>
      </main>
    </>
  );
};

export default Home;
