import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button, Container } from "reactstrap";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className="py-5 text-center">
          <h1 className="mt-5 display-1">
            O melhor jeito de comprar o que você ama
          </h1>
          <p className="my-4">
            Aqui, celebramos a excelência tecnológica que redefine a forma como
            vivemos, trabalhamos e nos conectamos. Explore a nossa vasta seleção
            de iPhones, iPads, MacBooks e muito mais, todos projetados para
            elevar sua experiência digital a novos patamares. Deixe-se envolver
            pela magia dos dispositivos Apple, onde o design meticuloso encontra
            a funcionalidade intuitiva. Complemente seu estilo de vida digital
            com acessórios exclusivos, desde capas elegantes até fones de ouvido
            de alta fidelidade.
          </p>
          <Link href="/products">
            <Button color="dark" className="px-4 pb-2">
              Conheça nossos produtos!
            </Button>
          </Link>
        </Container>
      </main>
    </>
  );
};

export default Home;
